name: Smoke test
on: push
jobs:
  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: bash ./bash_command_timer.sh
      - run: bash -c 'source ./bash_command_timer.sh; BCTPostCommand; BCTPreCommand; sleep 1; BCTPostCommand;'

